spring:
  datasource:
    url: jdbc:postgresql://csd-asssignment-g3-1.postgres.database.azure.com:5432/tariff?sslmode=require
    username: dev_sonia
    password: Gjk0a4*u
    driver-class-name: org.postgresql.Driver

security:
  jwt:
    secret-key: kAQMAOIq35Q4pwquvfXtKp9uQ5RexPxWqeCj+I918KQ=