# === base URL (Swap when changing from local to deployment) ===

# Local backend (when running Spring Boot on your laptop)
@baseUrl = http://localhost:8080

# Azure deployed backend (when app is live on Azure App Service)
# @baseUrl = https://csd-asssignment-g3-1.azurewebsites.net

# === 1. REGISTRATION OF AN ACCOUNT ===
### Registration of an Account
POST {{baseUrl}}/api/v1/auth/register
Content-Type: application/json

{
  "username": "notjeff",
  "email": "jeff@example.com",
  "password": "Abcd1234"
}

# === 2. LOGGING INTO AN ACCOUNT ===  
### Logging into an Account
POST {{baseUrl}}/api/v1/auth/login
Content-Type: application/json

{
  "username": "notjeff",
  "password": "Abcd1234"
}

# === 3. VALIDATION OF TOKEN ===
### Validation of account token
GET {{baseUrl}}/api/v1/auth/validate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNiIsImlhdCI6MTc1ODgxOTYwMiwiZXhwIjoxNzU4OTA2MDAyLCJlbWFpbCI6Im1hcmNsaW0xMkBleGFtcGxlLmNvbSJ9.v8spcXzOX01YMgyKya74toJP-BQ6YDyR7u0K6C9CvWM

### Get current user information
GET {{baseUrl}}/api/v1/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNiIsImlhdCI6MTc1ODgxOTYwMiwiZXhwIjoxNzU4OTA2MDAyLCJlbWFpbCI6Im1hcmNsaW0xMkBleGFtcGxlLmNvbSJ9.v8spcXzOX01YMgyKya74toJP-BQ6YDyR7u0K6C9CvWM
# === 5. LOGGING OUT OF AN ACCOUNT ===
### Logout user (Delete mapping)
DELETE {{baseUrl}}/api/v1/auth/logout
Authorization: Bearer PASTE_ACCESS_TOKEN_HERE